- name: Configure web servers
  hosts: web
  become: true
  
  tasks:
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        update_cache: yes
        state: present

    - name: Create directory structure for web documents
      ansible.builtin.file:
        path: /web/html
        state: directory
        mode: '0755'

    - name: Copy nginx conf file to server
      ansible.builtin.copy:
        src: files/nginx.conf
        dest: /etc/nginx/sites-available/default
        mode: '0644'

    - name: Create link to nginx config file to enable it
      ansible.builtin.file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link

    - name: Generate index.html file from template
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: /web/html/index.html
        mode: '0755'

    - name: Reload nginx service
      ansible.builtin.service:
        name: nginx
        enabled: true
        state: reloaded
